### ISSUE TITLE
Pixel 8 Pro | Cant enable 5G | NSG | Rooted

### ISSUE THREAD

**Issue by Absarock** [TCattd/Pixel-VoLTE-VoWIFI-5G-Enabler#2]
hello,

I flashed this module on pixel 8 pro and am still unable to run 5G network. On Android 14, I was able to run 5G via "Pixel-VoLTE-VoWIFI-5G-Enabler" module and Network Signal Guru App. I dont remember what exactly I did other than enabling all the modes in "NR mode setting". I have upgraded to Android 15 now. 

Can someone assist? Thank you

![Screenshot_20241016-042215](https://github.com/user-attachments/assets/cfbd9cb7-a3cb-4849-b80b-9010d519d0b4)
![Screenshot_20241016-042241](https://github.com/user-attachments/assets/d0d9c627-8023-4683-a98c-c1ffc93333c5)

**Comment by TCattd** [comment]
No, i haven't upgrade to Android 15. Don't like betas on the daily driver.

Please, take a look: https://github.com/TCattd/Pixel-VoLTE-VoWIFI-5G-Enabler?tab=readme-ov-file#disclaimer
